config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "registrations"}, :path => '', :path_names => { :sign_in=>'login', :sign_out=>'logout' }
  resources :users, only: [:show, :edit, :update]
  
  resources :products do
    resources :testimonials
  end
  resources :articles do
    resources :comments
  end

  resources :payments

  root 'pages#landing_page'

  get 'about', to: 'pages#about'

  get 'destinations', to: 'products#index'

  get 'contact', to: 'contact#form_in'

  post 'form_out', to: 'contact#form_out'

  get 'faq', to: 'pages#faq'

  get 'form_input', to: 'form_example#form_input'

  get 'form_output', to: 'form_example#form_output'

  get 'blog', to: 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

  attr_accessible :title, :author, :date, :body

  has_many :comments

  validates :title, :author, :date, :body, presence: true
  validates :title, :author, uniqueness: true
  validates :title, length: { maximum: 30 }
  validates :author, length: { maximum: 30 }
  validates :body, length: { in: 20..300 }
  validates :date, length: { is: 10 }
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ActiveModel::MassAssignmentSecurity
  load_and_authorize_resource

  attr_protected :title, :author, :date, :body

  #GET /articles
  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 4)
  end

  #GET /articles/1
  def show
  end

  #GET /articles/new 
  def new
    @article = Article.new
  end

  #GET /articles/1/edit
  def edit
  end

  #POST /articles
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  #PATCH/PUT /articles/1
  def update
    respond_to do |format|
      if @article.update(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  #DESTROY /articles/1
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

	def cache_key_for_articles
		max_updated_at = Article.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"articles/page-#{params[:page]}-#{max_updated_at}"
	end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
	<% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, 'error') %> prohibited this article from being saved:</h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
	<% end %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, {class: 'form-control', placeholder: 'Title', required: 'true', maxlength: '60', autofocus: true} %>
  </div>
  <div class="form-group">
    <%= f.label :author %><br>
    <%= f.text_field :author, {class: 'form-control', placeholder: 'Author', required: 'true', maxlength: '50'} %>    
  </div>
  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.text_field :date, {class: 'form-control', placeholder: 'Date', required:'true'} %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, {class: 'form-control', placeholder: 'Body', rows: '10', required: 'true', maxlength: '300'} %>
  </div>
  <div class="actions">
    <%= f.submit nil, {class:'btn btn-success'} %>
  </div>
<% end %>
							

app/views/articles/_newest_articles.html.erb
 <hr>
 <div class="row-testimonials">
  <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="panel-title">Lastest Articles</h2>
      </div>
      <div class="panel-body">
        <% Article.order(updated_at: :desc).limit(3).each do |article| %>
          <ul class="list-group">
            <li class="list-group-item"><%= link_to article.title, article %></li>
          </ul>
        <% end %> 
      </div>   
    </div>
  </div> <!-- col-xs-7 col-sm-7 col-md-7 col-lg-7 -->
</div> <!-- row-testimonials -->

app/views/articles/edit.html.erb
<div class="content">
  <div class="container">
    <div class="row-testimonials">
      <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7">
        <h1>Edit Article</h1>
        <%= render 'form' %>
        <%= link_to 'Show', @article %> |
        <%= link_to 'Back', articles_path %>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<% @body_id = 'blog' %>

<div class="content">
  <div class="container">
    <div class="row-testimonials">
      <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h2 class="panel-title">Articles</h2>
          </div>
          <div class="panel-body">
            <% cache(cache_key_for_articles) do %>
              <% @articles.order(updated_at: :desc).each do |article| %>
                <ul class="list-group">
                  <li class="list-group-item">
                    <% cache(article) do %>
                      <%= link_to article.title, article_url(article) %>
                    <% end %>
                  </li>
                </ul>
              <% end %> 
            <% end %>       
            <ul class="pagination list-group">
              <li class="a-left"><%= will_paginate @articles %></li>
            </ul>
            <p class="navigation a-right">
              <%= link_to 'New Article', new_article_path %>
            </p>        
          </div>   
        </div>
      </div> <!-- col-xs-8 col-sm-8 col-md-8 col-lg-8 -->
    </div> <!-- row-testimonials -->
  </div> <!-- container -->
</div> <!-- content -->

app/views/articles/new.html.erb
<div class="container">
  <div class="row-testimonials">
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
      <%= form_for(@article) do |f| %>
        <% if @article.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@article.errors.count, 'error') %> prohibited this article from being saved:</h2>
            <ul>
              <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, {class: 'form-control', placeholder: 'Title', required: true, maxlength: '60', autofocus: true} %>
        </div>
        <div class="form-group">
          <%= f.label :author %><br>
          <%= f.text_field :author, {class: 'form-control', placeholder: 'Author', required: true, maxlength: '50'} %>    
        </div>
        <div class="form-group">
          <%= f.label :date %><br>
          <%= f.text_field :date, {class: 'form-control', placeholder: 'Date', required: true} %>
        </div>
        <div class="form-group">
          <%= f.label :body %><br>
          <%= f.text_area :body, {class: 'form-control', placeholder: 'Body', rows: '10', required: true} %>
        </div>
        <div class="actions">
          <%= f.submit nil, {class:'btn btn-success'} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="content">
  <div class="container article">
    <div class="row-feature">
      <div class="col-xs-8 col-sm-8 col-md-8 col-lg8">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h2 class="panel-title"><%= @article.title %><span class="a-right glyphicon glyphicon-plane"></span></h2>
          </div>
          <div class="panel-body">
            <ul class="article">
              <li>By: <%= @article.author %></li>
              <li><span class="glyphicon glyphicon-calendar"></span></li>
              <li><%= @article.updated_at.strftime( "%A, %d %b %Y %H:%M" ) %></li>
            </ul>
             <hr class="article">
             <p><%= @article.body %></p>
          </div>
          <div class="panel-footer">
            <ul>
              <li><%= link_to 'Edit', edit_article_path(@article) %></li> |
              <li><%= link_to 'Delete', @article, method: :delete, data: {confirm: 'Are you sure?'} %></li> |
              <li><%= link_to 'Back', articles_path %></li>
            </ul>
          </div>
        </div>
        <div>
          <p><h2>Add a Comment</h2></p>
          <%= form_for([@article, @article.comments.build]) do |f| %>
            <p>
              <%= f.label :commenter %><br>
              <%= f.text_field :commenter %>
            </p>
            <p>
              <%= f.label :body %><br>
              <%= f.text_area :body %>
            </p>
            <p>
              <%= f.submit %>
            </p>
          <% end %>
        </div>
        <div>
          <% unless @article.comments.first.new_record? %>
            <p><h2>Comments</h2></p>
            <% cache(cache_key_for_comments) do %>
              <% @article.comments.each do |comment| %>
                <% unless comment.new_record? %>
                  <p>
                    <strong>Commenter:</strong>
                    <% cache(comment.commenter) do %>
                      <%= comment.commenter %>
                    <% end %>
                  </p>
                  <p>
                    <strong>Comment:</strong>
                    <% cache(comment.body) do %>
                      <%= comment.body %>
                    <% end %>
                  </p>
                    <% cache((comment.id).to_s + "destroy") do %>
                      <%= link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>