config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "registrations"}, :path => '', :path_names => { :sign_in=>'login', :sign_out=>'logout' }
  resources :users, only: [:show, :edit, :update]
  
  resources :products do
    resources :testimonials
  end
  resources :articles do
    resources :comments
  end

  resources :payments

  root 'pages#landing_page'

  get 'about', to: 'pages#about'

  get 'destinations', to: 'products#index'

  get 'contact', to: 'contact#form_in'

  post 'form_out', to: 'contact#form_out'

  get 'faq', to: 'pages#faq'

  get 'form_input', to: 'form_example#form_input'

  get 'form_output', to: 'form_example#form_output'

  get 'blog', to: 'articles#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities



    user ||= User.new
    if user.is_admin?
        can :manage, :all
    else
        can :read, :all
        can :manage, user
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base

  attr_accessible :title, :author, :date, :body

  has_many :comments

  validates :title, :author, :date, :body, presence: true
  validates :title, :author, uniqueness: true
  validates :title, length: { maximum: 30 }
  validates :author, length: { maximum: 30 }
  validates :body, length: { in: 20..300 }
  validates :date, length: { is: 10 }
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

  attr_accessible :commenter, :body

  validates :commenter, :body, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base

	attr_accessible :name, :description, :image_src, :price, :months, :featured

 	has_many :testimonials
  	
  validates :name, :description, :image_src, :price, :months, presence: true
  validates :name, length: { maximum: 15 }
  validates :description, length: { in: 20..200 }
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ },  :numericality => { :greater_than => 0, :less_than => 10000 }


end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  belongs_to :product
  attr_accessible :name, :email, :body
  
  validates :name, :email, :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :customer_id, :password, :password_confirmation

  def charge(options)

    cus=Stripe::Customer.create(card: options[:stripeToken], email: email)
    update_attributes customer_id: cus.id
    
    Stripe::Charge.create(
    	:customer    => cus.id,
    	:amount      => 10000,
    	:description => '1 Tour',
    	:currency    => 'GBP'
		)

  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ActiveModel::MassAssignmentSecurity
  load_and_authorize_resource

  attr_protected :title, :author, :date, :body

  #GET /articles
  def index
    @articles = Article.paginate(:page => params[:page], :per_page => 4)
  end

  #GET /articles/1
  def show
  end

  #GET /articles/new 
  def new
    @article = Article.new
  end

  #GET /articles/1/edit
  def edit
  end

  #POST /articles
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  #PATCH/PUT /articles/1
  def update
    respond_to do |format|
      if @article.update(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  #DESTROY /articles/1
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActiveModel::MassAssignmentSecurity

  attr_protected :commenter, :body
  load_and_authorize_resource
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment])
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def form_in
  end
  def form_out
    @mail = ActionMailer::Base.mail(:from => params[:email], :to => "ammj24@hotmail.com", :subject => params[:subject], 
        :body => params[:message]).deliver
    flash[:notice] = "Thanks for your submission. We will contact you as soon as possible."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing_page
   @featured_products = Product.where(featured: true).all
  end
  def about
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  include ActiveModel::MassAssignmentSecurity

  skip_before_action :verify_authenticity_token

  attr_protected :customer_id

  def create

  	respond_to do |format|
	    if current_user.charge(params)
	    	format.html { redirect_to :back, notice: 'Product has been successfully charged.' }
	    	format.js {}
	    	format.json { render json: :back, status: :created }
	    else
	      format.html { redirect_to :back, alert: 'Product has not been charged.' }
	      format.js {}
	    	format.json { render json: :back, status: :created }
	    end
  	end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ActiveModel::MassAssignmentSecurity

  attr_protected :email, :customer_id, :password, :password_confirmation
  before_filter :authenticate_user!
  load_and_authorize_resource

  def show
  end

  def edit
  end

  def update
    @user.update_attributes(params[:user])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def cache_key_for_articles
		max_updated_at = Article.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"articles/page-#{params[:page]}-#{max_updated_at}"
	end
end

app/helpers/comments_helper.rb
module CommentsHelper

	def cache_key_for_comments
		article = Article.find(params[:id])
		count = Comment.count
		max_updated_at = Article.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"#{article.id}/comments/id-#{count}-#{max_updated_at}"
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	def cache_key_for_products
		count = Product.count
		max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"products/all-#{count}-#{max_updated_at}"
	end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper

	def cache_key_for_testimonials
		product = Product.find(params[:id])
		count = Testimonial.count
		max_updated_at = Testimonial.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"#{product.id}/testimonials/id-#{count}-#{max_updated_at}"
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<hr>
	<div class="container footer">
		<div class="fb-like-box" data-href="https://www.facebook.com/natgeo" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true" data-share="true"></div>
		<div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-type="button_count"></div>
		<nav>
			<ul class="nav">
				<li><%= link_to 'FAQ', faq_path, 'id'=>'nav-faq' %>
				<li><%= link_to 'Terms', "#" %>
				<li><%= link_to 'Privacy', "#", data: {target: "#privacy", toggle: "modal", keyboard: "true"}  %>
			</ul>
		</nav>
		<div class="modal fade" id="privacy" tabindex="-1">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button class="close" data-dismiss="modal">&times;</button>
						<h3>Privacy Policy</h3>
					</div><!-- .modal-header -->
					<div class="modal-body">
						<p>We respect your privacy! We will not misuse nor sell any information provided to us. All of your information provided to us is for the express purpose of processing your order. By supplying such information, we will retain only the information needed to complete your order. Any information provided to us will not be shared with any other company or third party.</p>
					</div><!-- .modal-body -->
				</div><!-- .modal-content -->
			</div><!-- .modal-dialog -->          
		</div><!-- .modal -->
		<!-- Begin MailChimp Signup Form -->
		<div id="mc_embed_signup">
			<form action="https://onjumpstarter.us8.list-manage.com/subscribe/post?u=a0767ebdd4eab0f955b33d4cb&amp;id=c2ed91adda" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
				<label for="mce-EMAIL">Subscribe to our mailing list</label>
				<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email@address.com" required>
					<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
					<div style="position: absolute; left: -5000px;"><input type="text" name="b_a0767ebdd4eab0f955b33d4cb_c2ed91adda" tabindex="-1" value=""></div>
					<input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-info">
			</form>
		</div>
		<!--End mc_embed_signup-->
		<p>Copyright &copy; 2014 The Adventure Company</p>
	</div><!-- .container -->
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>  
  
  <nav class="fixed">   
    <div class="nav-header">  
      <div class="hidden-xs">
        <p class="nav-logo">The Adventure Traveller</p>
        <div class="nav-login">
          <ul class="navbar">
            <% if user_signed_in? %>
              <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, 'id'=>'nav-signout' %></li>         
            <% else %>
              <li><%= link_to 'Log In', new_user_session_path, 'id'=>'nav-signin' %> |
              <%= link_to 'Sign Up', new_user_registration_path, 'id'=>'nav-signup' %></li>
            <% end %>
          </ul>
        </div>
        <ul class="navbar">
          <li><%= link_to 'Home', root_path, 'id'=>'nav-home' %>
          <li><%= link_to 'About', about_path, 'id' => 'nav-about' %>
          <li><%= link_to 'Destinations', destinations_path, 'id'=>'nav-destinations' %>
          <li data-no-turbolink><%= link_to 'Contact', contact_path, 'id'=>'nav-contact' %>
          <li><%= link_to 'Blog', blog_path, 'id'=>'nav-blog' %>
        </ul>
        <!-- login -->
        <% if user_signed_in? %>
          <ul class="login">
            <li>You are logged in as:</li>
            <li class="dropdown">
              <%= link_to raw(current_user.email + '<span class="caret"></span>'), '', 'class'=>'dropdown-toggle', 'data-toggle'=>'dropdown', 'id'=>'nav-profile' %>
              <ul class="dropdown-menu profile">
                <% if current_user.is_admin == true %>
                  <li><%= link_to 'Admin Dashboard', rails_admin_path %>
                <% elsif %>
                  <li><%= link_to 'Profile', user_path(current_user.id) %>
                <% end %>
              </ul>
            </li>
          </ul>
        <% end %>
   
        <% flash.each do |key, value| %>
          <% if key == 'alert' %>
            <div class="alert alert-danger message"><%=value%></div>
          <% elsif key == 'notice' %>
            <div class="alert alert-success message"><%=value%></div>
          <% end %>
        <% end %>
      </div><!-- .hidden-xs -->   
    </div> <!-- .nav-header -->
  </nav> <!-- .fixed -->

  <nav class="fixed">
    <div class="nav-header-mobile">
      <div class="visible-xs">
        <p class="nav-logo-mobile">The Adventure Traveller</p>
        <button class="navbar-toggle collapsed nav-button" data-target=".navbar-collapse" data-toggle="collapse" type="button">&#9776;</button> 
        <center>
          <div class="collapse navbar-collapse" >
            <ul class="navbar-mobile" >
              <li><%= link_to 'Home', root_path, 'id'=>'nav-home' %>
              <li><%= link_to 'About', about_path, 'id' => 'nav-about' %>
              <li><%= link_to 'Destinations', destinations_path, 'id'=>'nav-destinations' %>
              <li data-no-turbolink><%= link_to 'Contact', contact_path, 'id'=>'nav-contact' %>
              <li><%= link_to 'Blog', blog_path, 'id'=>'nav-blog' %>
              <% if user_signed_in? %>
                <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, 'id'=>'nav-signout' %></li> 
              <% else %>
                <li><%= link_to 'Log In', new_user_session_path, 'id'=>'nav-signin' %>|
                <%= link_to 'Sign Up', new_user_registration_path, 'id'=>'nav-signup' %></li>
              <% end %>
            </ul>
            <!-- login -->
            <% if user_signed_in? %>
              <ul class="login">
                <li>You are logged in as:</li>
                <li class="dropdown">
                  <%= link_to raw(current_user.email + '<span class="caret"></span>'), '', 'class'=>'dropdown-toggle', 'data-toggle'=>'dropdown', 'id'=>'nav-profile' %>
                  <ul class="dropdown-menu profile">
                    <% if current_user.is_admin == true %>
                      <li><%= link_to 'Admin Dashboard', rails_admin_path %>
                    <% elsif %>
                      <li><%= link_to 'Profile', user_path(current_user.id) %>
                    <% end %>
                  </ul>
                </li>
              </ul>
            <% end %>
          </div> <!-- .collapse navbar-collapse -->
        </center>
        <% flash.each do |key, value| %>
          <% if key == 'alert' %>
            <div class="alert alert-danger message"><%=value%></div>
          <% elsif key == 'notice' %>
            <div class="alert alert-success message"><%=value%></div>
          <% end %>
        <% end %>
      </div> <!-- .visible-xs -->  
    </div><!-- .nav-header-mobile -->
  </nav><!-- .fixed -->

  <div class="hidden-xs">
    <div class="space">
      <div id="content">
        <div data-ride="carousel"  class="carousel slide" id="myCarousel">
          <ol class="carousel-indicators">
            <li class="" data-slide-to="0" data-target="#myCarousel"></li>
            <li data-slide-to="1" data-target="#myCarousel" class="active"></li>
            <li data-slide-to="2" data-target="#myCarousel" class=""></li>
          </ol>
          <div class="carousel-inner">
            <div class="item active">
              <img src="/images/_hero-images/hero_Iceland.jpg" alt="">
              <div class="container">
                <h1>Example Headline</h1>
                <p>A longer summary of what we do</p>
                <p><%= link_to 'Sign up today', new_user_registration_path, 'role'=>'button', 'class'=>'btn btn-lg btn-info'%></p>
              </div><!-- .container -->
            </div><!-- .item -->
            <div class="item">
              <img src="/images/_hero-images/hi-machu-pichu.jpg" alt="">
              <div class="container">
                <h1>Second Headline</h1>
                <p>Description of the second slide</p>
                <p><a role="button" href="#" class="btn btn-lg btn-info">Read more here</a></p>
              </div><!-- .container -->
            </div><!-- .item -->
            <div class="item">
              <img src="/images/_hero-images/hero_desert.jpg" alt="">
              <div class="container">
                <h1>Third Headline</h1>
                <p>One more slide about the product</p>
                <p><a role="button" href="#" class="btn btn-lg btn-info">Features</a></p>
              </div><!-- .container -->
            </div><!-- .item -->
          </div><!-- .carousel inner -->
          <a data-slide="prev" href="#myCarousel" class="left carousel-control"><span class="glyphicon glyphicon-chevron-left"></span></a>
          <a data-slide="next" href="#myCarousel" class="right carousel-control"><span class="glyphicon glyphicon-chevron-right"></span></a>
        </div><!-- .carousel -->
      </div><!-- .content -->
    </div><!-- .space -->
  </div><!-- .hidden-xs -->

  <div class="visible-xs">
    <div class="space-mobile">
      <div id="content">
        <div data-ride="carousel"  class="carousel slide" id="myCarousel">
          <ol class="carousel-indicators">
            <li class="" data-slide-to="0" data-target="#myCarousel"></li>
            <li data-slide-to="1" data-target="#myCarousel" class="active"></li>
            <li data-slide-to="2" data-target="#myCarousel" class=""></li>
          </ol>
          <div class="carousel-inner">
            <div class="item active">
              <img src="/images/_hero-images/mobile/hero_Iceland.jpg" alt="">
              <div class="container">
                <h1>Example Headline</h1>
                <p>A longer summary of what we do</p>
                <p><%= link_to 'Sign up today', new_user_registration_path, 'role'=>'button', 'class'=>'btn btn-lg btn-info'%></p>
              </div><!-- .container -->
            </div><!-- .item -->
            <div class="item">
              <img src="/images/_hero-images/mobile/hi-machu-pichu.jpg" alt="">
              <div class="container">
                <h1>Second Headline</h1>
                <p>Description of the second slide</p>
                <p><a role="button" href="#" class="btn btn-lg btn-info">Read more here</a></p>
              </div><!-- .container -->
            </div><!-- .item -->
            <div class="item">
              <img src="/images/_hero-images/mobile/hero_desert.jpg" alt="">
              <div class="container">
                <h1>Third Headline</h1>
                <p>One more slide about the product</p>
                <p><a role="button" href="#" class="btn btn-lg btn-info">Features</a></p>
              </div><!-- .container -->
            </div><!-- .item -->
          </div><!-- .carousel inner -->
          <a data-slide="prev" href="#myCarousel" class="left carousel-control"><span class="glyphicon glyphicon-chevron-left"></span></a>
          <a data-slide="next" href="#myCarousel" class="right carousel-control"><span class="glyphicon glyphicon-chevron-right"></span></a>
        </div><!-- .carousel -->
      </div><!-- .content -->
    </div><!-- .space -->
  </div><!-- .visible-xs -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Adventure Traveller</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
    <link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196">
    <link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160">
    <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-TileImage" content="/mstile-144x144.png">
  </head>
  <body id="<%= @body_id %>">
    <%= render '/layouts/header' %>
    <%= yield %>
    <%= render '/layouts/footer' %>
    <script>
    !function($){
      $('.lightbox').magnificPopup({
        delegate: 'a',
        type: 'image',
        gallery: { enabled: true}
      });
    }(window.jQuery);
    </script>
  </body>
</html>

app/views/pages/_featured_product.html.erb
<hr>
<% @featured_products.each do |p| %>
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"> 
    <%= link_to image_tag("#{p.image_src}", {:class=>'img-responsive', :alt=>"#{p.name}", :height=>"250px"}), product_path(p.id) %>
    <h3><%= link_to "#{p.name}", product_path(p.id) %></h3>
  </div><!-- .col-lg-4  -->
<% end %>

app/views/pages/about.html.erb
<% @body_id='about' %>
<div id="content">
  <div class="container">
    <h3>About the Company</h3>
    <p>Do eiusmod tempor incididunt ut labore et dolore magna aliqua. Totam rem aperiam. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Architecto beatae vitae dicta sunt explicabo. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.
    <p>Facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Excepteur sint occaecat cupidatat non proident, sunt in culpa. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Qui officia deserunt mollit anim id est laborum. Do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

    <h3>About the Team</h3>
    <p>Do eiusmod tempor incididunt ut labore et dolore magna aliqua. Totam rem aperiam. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Architecto beatae vitae dicta sunt explicabo. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.
    <p>Facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Excepteur sint occaecat cupidatat non proident, sunt in culpa. Quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Qui officia deserunt mollit anim id est laborum. Do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  </div>
</div>

app/views/pages/signup.html.erb
<% @body_id='signup' %>
<div id="content">
 
</div><!-- #content -->

app/views/shared/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="/images/logo.png"
  data-name="The Adventure Traveller"
  data-description="1 Tour"
  data-amount=10000
  data-currency="GBP">
</script>